### PR TITLE
chore: remove unnecessary `declare module` block in typings

### PR DESCRIPTION
**Pull request by JounQin**
The typings are in its own package, so `declare module` is redundant.

### CODE REVIEW

**Comment by JounQin** [comment]
ping @wojtekmaj

**Comment by wojtekmaj** [comment]
In this case, what about entry.nostyle.d.ts?

**Comment by JounQin** [comment]
> In this case, what about entry.nostyle.d.ts?

@wojtekmaj 

It is not `types` in `package.json`, or the same dir as `dist/entry.nostyle .js`, so its `declare module` is required, and this PR will not break that.

Personally, I would prefer to have `entry.nostyle.d.ts` at `dist/entry.nostyle.d.ts`, then no `declare module` is required.

**Comment by wojtekmaj** [comment]
No longer relevant as React-Date-Picker is now natively in TypeScript.

**Pull request closed without merging**
