### PR TITLE
Fix picking date on Safari in modal

### PR DESCRIPTION
**Pull request by creativeBernadka**
# Bug description

When date picker is placed in modal and used with Safari browser the user is unable to select a date.

# Related issues

[1] https://github.com/wojtekmaj/react-date-picker/issues/288

### CODE REVIEW

**Comment by ron51** [comment]
@creativeBernadka hey will issue be merged anytime soon? Does is resolve the issue?

**Comment by creativeBernadka** [comment]
Hey @ron51! Yeah, it solves the issue but it doesn't pass some tests. I think that in this or next week I should work on fixing the tests. So than it could be merged

**Comment by ron51** [comment]
@creativeBernadka thank you for the prompt reply, waiting for this fix.

**Comment by Ranthonym** [comment]
@creativeBernadka Hey just wanted to note that this bug still persists. Was the fix ever deployed?

**Comment by rscotten** [comment]
Hello, I'm also having this problem.  @creativeBernadka @wojtekmaj can you please merge?

**Pull request closed without merging**
