### PR TITLE
Fixed HTMLCollection issue with older versions of Edge and IE

### PR DESCRIPTION
**Pull request by mathieumg**
Fixed issue where iterating an HTMLCollection would cause issues in older versions of Edge and IE.

### CODE REVIEW

**Comment by wojtekmaj** [comment]
Hi @mathieumg,
these lines:

```js
      // Wrapper was directly clicked
      const [/* nativeInput */, firstInput] = event.target.children;
      focus(firstInput);
```

are transpiled by Babel:

```js
        // Wrapper was directly clicked
        var _event$target$childre = _slicedToArray(event.target.children, 2),

        /* nativeInput */
        firstInput = _event$target$childre[1];

        focus(firstInput);
```

So I don't see how it could become a problem in production?

**Comment by mathieumg** [comment]
Yes, and the `_slicedToArray` utility ultimately iterates on `event.target.children`, which is a `HTMLCollection`. (Not iterable in Edge until version 17)

**Comment by wojtekmaj** [comment]
Ah, I understand now! Thank you for the explanation and sorry to keep you waiting.

**Comment by wojtekmaj** [comment]
Added this to React-DateTime-Picker and React-Time-Picker too, marking you as co-author. :)

**Comment by mathieumg** [comment]
No problem, thank you! 😎

**Pull request merged**
