### PR TITLE
fix extra zeros cases with showLeadingZeros

### PR DESCRIPTION
**Pull request by antoniojmartnez**
Hi,

I expose a possible solution to the extra zero problem when showLeadingZeros is being used and a zero is entered first.

Regards

### CODE REVIEW

**Comment by wojtekmaj** [comment]
I like this concept! Thanks for your contribution.

**Comment by senitelty** [comment]
@wojtekmaj when will it be merged?

**Comment by alixaxel** [comment]
@wojtekmaj Is the CodeClimate review blocking this merge?

**Comment by wojtekmaj** [comment]
No. package-lock.json shouldn't be there, we're using Yarn, but I was just focused on different projects and personal stuff.

**Comment by wojtekmaj** [comment]
I found this PR to unfortunately behave unreliably between browsers. A definite fix will be introduced after https://github.com/wojtekmaj/react-date-picker/pull/272/ is merged since this will allow React-Date-Picker to know EXACTLY wat was inputted, and not just the number (without zeros).

**Pull request closed without merging**
